[package]
name = "cmdline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "=1.0.68"
e2eoffline = { version = "0.1.0", path = ".." }
